//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    public partial class GridSample
    {
        /// <summary>EmployeeGrid 컨트롤</summary>
        protected global::WebApp.Controls.AgGridControl EmployeeGrid;

        /// <summary>ProductGrid 컨트롤</summary>
        protected global::WebApp.Controls.AgGridControl ProductGrid;
    }
}
