//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Controls
{
    public partial class AgGridControl
    {
        // AgGridControl.ascx 내부에 runat="server" 컨트롤이 없으므로 비어 있음
    }
}
